### ISSUE TITLE
Add jinja2 templates to https://pyldapi.readthedocs.io/en/latest/download_jinja_templates.html

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/pyLDAPI#11]
Add downloadable templates to https://pyldapi.readthedocs.io/en/latest/download_jinja_templates.html

**Comment by edmondchuc** [comment]
Add downloadable templates to https://pyldapi.readthedocs.io/en/latest/download_jinja_templates.html

**Comment by nicholascar** [comment]
Edmond, can you do this or are you want ing me or Ashley to do something here?

**Comment by edmondchuc** [comment]
I can do this. I was thinking of providing a basic template to render the content for a register and an instance here. We can document what variables are required to be passed into the templates in the documentation.

**Comment by edmondchuc** [comment]
Oh I think I was in China or something when I remembered this task, so I added it as an issue because it was created 16 days ago.
