### ISSUE TITLE
reg:Register not appropriate as a generic container class

### ISSUE THREAD

**Issue by dr-shorthair** [RDFLib/pyLDAPI#17]
The class `reg:Registry` is defined in the [Registry Ontology](http://purl.org/linked-data/registry) . 

The Registry Ontology was designed to follow the ISO 19135 registration model, which focuses primarily on 'registration' as an activity, relating to endorsement, identifier assignment, and lifecycle. A `Register` is a collection of `RegisterItems`. But note that a `RegisterItem` is "A metadata record for an entry in a register. " The actual entity is two more steps removed, via the path `reg:definition/reg:entity`. 

![image](https://user-images.githubusercontent.com/608303/68093843-0b7e2a00-feee-11e9-9f8b-a51b8b124c84.png)

I don't think this is the sense that it is being used in pyLDAPI, where it is being used a generic container for either 'features' (i.e. individual objects) or nested containers.

**Comment by dr-shorthair** [comment]
FWIW - https://www.w3.org/TR/rdf-schema/#ch_containervocab

**Comment by dr-shorthair** [comment]
And maybe better: https://www.w3.org/TR/ldp/#ldpc

**Comment by dr-shorthair** [comment]
Having explored the documentation around RDF containers - e.g. https://www.w3.org/2007/02/turtle/primer/#L2581 https://www.oreilly.com/library/view/practical-rdf/0596002637/ch04.html I'm coming around to thinkng that `rdf:Bag` or `rdf:Collection`, together with `rdfs:member` is the generic case.

**Comment by dr-shorthair** [comment]
(of course `rdfs:member` points in the opposite direction to `reg:register` but that only requires SPARQL graph patterns to have the occasional line reversed.)

**Comment by nicholascar** [comment]
Conneg by P branch of this repo now in test. I’ll make this change once the ConnegP branch has been merged into master.

**Comment by nicholascar** [comment]
Moved to `rdf:Bag` with suggested `rdfs:member` as of v3.3 https://github.com/RDFLib/pyLDAPI/commit/03b9b38ac014b00c996825b92fa10caa6d840437
