### ISSUE TITLE
Enable CORS for browser client consumption

### ISSUE THREAD

**Issue by benjaminleighton** [RDFLib/pyLDAPI#18]
Alternates view endpoints cannot be consumed in other browser clients because of CORS restrictions. Alternates views should return Access-Control-Allow-Origin: *

**Comment by nicholascar** [comment]
Addressed in 3.5 https://github.com/RDFLib/pyLDAPI/commit/e778a342a7784ad9e47fa6a8d588c05c07fd28f2
