### ISSUE TITLE
Hand _render_alternates_view() the self.uri value

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/pyLDAPI#2]

**Comment by ashleysommer** [comment]
Im making some updates to pyldapi. What is this issue about?
Why does `_render_alternates_view()` need/want the self.uri value. Also, why does it need to be handed it, it is an instance method so it can just call `self.uri` if it needs to get the instance property `uri` from itself.

**Comment by ashleysommer** [comment]
I see this issue is a copy of this one:
https://github.com/CSIRO-enviro-informatics/pyldapi/issues/2

Is it still relevant?

**Comment by nicholascar** [comment]
No longer relevant, closing.
