### ISSUE TITLE
Include Namespace for Alternates View in Rendered.__init__()

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/pyLDAPI#3]
So the alt view Namespace is always populated

**Comment by ashleysommer** [comment]
I might be misunderstanding this issue, but isn't the alt view namespace already included and populated?
https://github.com/RDFLib/pyLDAPI/blob/3c30d8d08308ac36a9903be69ba7c9fcba7131d5/pyldapi/renderer.py#L57

**Comment by ashleysommer** [comment]
I see this issue is a copy of this one:
https://github.com/CSIRO-enviro-informatics/pyldapi/issues/3

Is it still relevant?

**Comment by nicholascar** [comment]
We might have moved beyond this so this is now just a zombie issue. Let's close.
