### ISSUE TITLE
Redundant uri parameter in RegisterRenderer __init__()

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/pyLDAPI#7]
The pyldapi.RegisterRenderer() already contains a parameter for a Flask request object, which can get the uri/url. No need for business code to provide it as an additional argument. 

```python
r = pyldapi.RegisterRenderer(
        request,
        request.url, # <-- redundant
        'Sample Register',
        'A register of Samples',
        items,
        [conf.URI_SAMPLE_CLASS],
        no_of_items
)
```

**Comment by nicholascar** [comment]
`RegisterRenderer` has been replaced with `ContainerRenderer` which now has a property `instance_uri`.

This property is not redundant as the Container URI might need to be expressed with a persistent URI rather than the API endpoint URI if a PID URI is used to redirect to that Container.
